---
- hosts: pi
  gather_facts: false
  include_vars: vars/default.yml
  vars:
    host_domains: 'mail.{{domain}}'
    ldap_ip: '127.0.0.1'
    tls_cert_file_location: '/etc/letsencrypt/live/{{ host_domains.split(", ")[0] }}/fullchain.pem'
    tls_key_file_location: '/etc/letsencrypt/live/{{ host_domains.split(", ")[0] }}/privkey.pem'
    fail2ban_postfix: true
    fail2ban_dovecot: true
    ldap_user_searchbase: '{{ "ou=people,dc=" + domain.split(".") | join(",dc=") }}'
    ldap_service_searchbase: '{{ "ou=services,dc=" + domain.split(".") | join(",dc=") }}'
    autossh: true
    sshuttle: true
  tasks:
    - name: git clone letsencrypt
      git:
        repo: https://github.com/letsencrypt/letsencrypt
        dest: /opt/letsencrypt
        force: yes
  roles:
    - common
    - tunnel
    - letsencrypt_basic
    - openldap
    - mail
    - calendarserver

