---
- hosts: pi
  roles:
    - configuration
  tags:
    - configuration

- hosts: localhost
  tags:
    - configuration
  vars_files:
    - vars/custom.yml
  environment:
    AWS_DEFAULT_REGION: "{{ aws_region }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
    AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
  roles:
    - provision

- hosts: gateway
  tags:
    - configuration
  vars:
    fail2ban_postfix: false
    fail2ban_dovecot: false
    client_pub_key: "{{ lookup('file', '~/.ansible/tmp/temp_client_pubkey_file.pub') }}"
    openvpn_static_key: "{{ lookup('file', '~/.ansible/tmp/openvpn_static.key') }}"
  roles:
    - gateway

- hosts: pi
  gather_facts: true
  vars:
    host_domains: 'mail.{{domain}}'
    ldap_ip: '127.0.0.1'
    tls_cert_file_location: '/etc/letsencrypt/live/{{ host_domains.split(", ")[0] }}/fullchain.pem'
    tls_key_file_location: '/etc/letsencrypt/live/{{ host_domains.split(", ")[0] }}/privkey.pem'
    fail2ban_postfix: true
    fail2ban_dovecot: true
    ldap_user_searchbase: '{{ "ou=people,dc=" + domain.split(".") | join(",dc=") }}'
    ldap_service_searchbase: '{{ "ou=services,dc=" + domain.split(".") | join(",dc=") }}'
    openvpn_static_key: "{{ lookup('file', '~/.ansible/tmp/openvpn_static.key') }}"
  roles:
    - common
    - vpn-client
    - letsencrypt
    - openldap
    - mail
    - calendarserver
