---
- hosts: pi
  gather_facts: true
  vars_files:
    - vars/default.yml
  vars:
    host_domains: 'mail.{{domain}}'
    ldap_ip: '127.0.0.1'
    tls_cert_file_location: '/etc/letsencrypt/live/{{ host_domains.split(", ")[0] }}/fullchain.pem'
    tls_key_file_location: '/etc/letsencrypt/live/{{ host_domains.split(", ")[0] }}/privkey.pem'
    fail2ban_postfix: true
    fail2ban_dovecot: true
    ldap_user_searchbase: '{{ "ou=people,dc=" + domain.split(".") | join(",dc=") }}'
    ldap_service_searchbase: '{{ "ou=services,dc=" + domain.split(".") | join(",dc=") }}'
    openvpn_static_key: "{{ lookup('file', '~/.ansible/tmp/openvpn_static.key') }}"
  roles:
#    - common
#    - vpn-client
#    - letsencrypt
    - openldap
#    - mail
#    - calendarserver
