- name: generate DKIM private key
  command: openssl genrsa -out ~/.ansible/tmp/mail.private 1024
  tags:
    - configuration

- name: generate DKIM public key
  command: openssl rsa -in ~/.ansible/tmp/mail.private -out ~/.ansible/tmp/mail.public -pubout -outform PEM
  tags:
    - configuration

- name: check if DH key exists in temp location
  stat: path=~/.ansible/tmp/dh_1024.pem
  register: dhkey
  tags:
    - packages

- name: check if DH key exists in install location
  stat: path=/etc/postfix/certs/dh_1024.pem
  register: dhkey2
  become: yes
  tags:
    - packages

- name: create DH keys for PFS
  shell: openssl dhparam -2 -out dh_1024.pem 1024 chdir=~/.ansible/tmp/
  tags:
    - packages
  when: dhkey.stat.exists == false and dhkey2.stat.exists == false

- name: extract public key value
  shell: "cat ~/.ansible/tmp/mail.public | grep -v '^--' | tr -d '\n' > ~/.ansible/tmp/mail.dns"
  tags:
    - configuration

- name: load files into variables
  command: "cat ~/.ansible/tmp/mail.private"
  register: dkim_private
  tags:
    - configuration

- name: load files into variables
  command: "cat ~/.ansible/tmp/mail.public"
  register: dkim_public
  tags:
    - configuration

- name: load files into variables
  command: "cat ~/.ansible/tmp/mail.dns"
  register: dkim_dns
  tags:
    - configuration

- name: delete files
  file:
    name: "~/.ansible/tmp/{{ item }}"
    state: absent
  with_items: [ 'mail.private', 'mail.public', 'mail.dns', 'dh_1024.pem' ]
  when: preserve_keys is undefined
  tags:
    - configuration
    - packages
