---
  - name: check to see if a vault exists
    stat:
      path: ./files/vault.encrypted
    register: vault_file

  - include: user_input.yml
    when: vault_file.stat.exists != true

  - name: decrypt vault to a file
    command: ansible-vault decrypt ./files/vault.encrypted --output=./files/vault.decrypted
    when: vault_file.stat.exists

  - name: read in variables
    include_vars: ./files/vault.decrypted

    # set all variables for deployment here
  - name: set host facts
    set_fact:
      aws_access_key: '{{ vault_aws_access_key }}'
      aws_secret_key: '{{ vault_aws_secret_key }}'
      ldapadminpassword: '{{ vault_ldapadminpassword }}'
      caldavduserpassword: '{{ vault_caldavduserpassword }}'
      postfixuserpassword: '{{ vault_postfixuserpassword }}'
      domain: '{{ vault_domain }}'
      admin_email: '{{ vault_username }}@{{ vault_domain }}'
      ldap_org_name: '{{ vault_first_name }} {{ vault_last_name }}'
      emailusers:
        - username: '{{ vault_username }}'
          lastname: '{{ vault_last_name }}'
          firstname: '{{ vault_first_name }}'
          password: '{{ vault_password }}'
          uidnumber: 10001
          gidnumber: 5000
          fullname: '{{ vault_first_name }} {{ vault_last_name }}'

  - name: encrypt vault
    command: ansible-vault encrypt ./files/vault.decrypted --output ./files/vault.encrypted
    when: vault_file.stat.exists != true

  - name: delete decrypted
    file:
      path: ./files/vault.decrypted
      state: absent

  - name: generate ssh key if it doesn't exist
    user:
      name: "{{ ansible_user_id }}"
      generate_ssh_key: yes
      ssh_key_type: rsa
      ssh_key_bits: 2048

  - name: copy raspberry pi public ssh key to temp location
    copy:
      dest: ~/.ansible/tmp/temp_client_pubkey_file.pub
      src: ~/.ssh/id_rsa.pub

  - name: install openvpn
    package:
      name: openvpn
      state: latest
    become: yes

  - name: check to see if openvpn key exists
    stat:
      path: /etc/openvpn/static.key
    register: openvpn_key

  - name: create openvpn static key
    command: openvpn --genkey --secret /etc/openvpn/static.key
    become: yes
    when: openvpn_key.stat.exists != true

  - name: change permissions on static key file
    file: path=/etc/openvpn/static.key mode=0644
    become: yes

  - name: copy openvpn key to temp
    copy:
      src: /etc/openvpn/static.key
      dest: "/home/{{ansible_user}}/.ansible/tmp/openvpn_static.key"
    become: yes

  - name: change openvpn permissions back to readable only by root
    file: path=/etc/openvpn/static.key mode=0600
    become: yes
