---
  - name: setup privacylabs repository
    set_fact:
      apt_key_url: "http://repo.privacylabs.io/debian/gpg.key"
      apt_repo_url: [ 'deb http://repo.privacylabs.io/debian/ jessie main' ]
    when: ansible_architecture == "armv6l" or ansible_architecture == "armv7l"
    tags:
      - packages

  - name: Add privacylabs repo key
    apt_key:
      url: "{{ apt_key_url }}"
      state: present
      validate_certs: false
    become: yes
    when: ansible_architecture == "armv6l" or ansible_architecture == "armv7l"
    tags:
      - packages

  - name: Install privacylabs apt repository
    apt_repository:
      repo: '{{ item }}'
      state: present
    with_items: "{{ apt_repo_url }}"
    become: yes
    when: ansible_architecture == "armv6l" or ansible_architecture == "armv7l"
    tags:
      - packages

  - name: Install configurator
    apt:
      name: "{{ item }}"
      update_cache: yes
    with_items: [ 'oasis-configurator']
    become: yes
    when: ansible_architecture == "armv6l" or ansible_architecture == "armv7l"
    tags:
      - packages

  - name: install nginx
    apt:
      name: '{{ item }}'
    become: yes
    with_items: ['nginx']
    tags:
      - packages

  - name: Configure oasis nginx
    template:
      src: nginx-oasis.j2
      dest: /etc/nginx/sites-available/oasis
      owner: root
      group: root
      mode: 0644
    become: yes
    tags:
      - packages

  - name: Enable nginx oasis config
    file:
      src: /etc/nginx/sites-available/oasis
      dest: /etc/nginx/sites-enabled/default
      state: link
    become: yes
    tags:
      - packages
