---
aws_region: 'us-west-2'
digital_ocean_api_token: ''
preserve_keys: true
aws_instance_type: 't2.nano'
#terminate_gateway: yes
#public_ip: ''
#letsencrypt_staging: yes
dns1: 208.67.222.222
dns2: 208.67.220.220
#start_vpn: yes
