---
preserve_keys: true
skip_letsencrypt: yes
image_creation: yes
ldapadminpassword: 'default'
caldavduserpassword: 'default'
postfixuserpassword: 'default'
domain: 'default'
admin_email: 'pi@raspberrypi.local'
ldap_org_name: 'Example Organization'
ansible_user_id: 'pi'
emailusers:
  - username: pi
    lastname: Pi
    firstname: Raspberry
    password: raspberry
    uidnumber: 10001
    gidnumber: 5000
    fullname: Raspberry Pi
