---
cloud: 'aws'
aws_region: 'us-west-2'
digital_ocean_api_token: ''
preserve_keys: true
aws_instance_type: 't2.nano'
terminate_gateway: yes
#public_ip: ''
#letsencrypt_staging: yes

ldapadminpassword: 'raspberry'
caldavuserpassword: 'raspberry'
postfixuserpassword: 'raspberry'
domain: 'raspberrypi.local'


#admin_email: '{{ vault_username }}@{{ vault_domain }}'
#ldap_org_name: '{{ vault_first_name }} {{ vault_last_name }}'
