---
  - name: install openvpn
    package:
      name: openvpn
      state: latest
    tags:
      - packages

  - name: check to see if openvpn key exists
    stat:
      path: /etc/openvpn/static.key
    register: openvpn_key
    tags:
      - configuration

  - name: create openvpn static key
    command: openvpn --genkey --secret /etc/openvpn/static.key
    when: openvpn_key.stat.exists != true and openvpn_static_key is not defined
    tags:
      - configuration

  - name: copy openvpn static key
    copy:
      content: "{{ openvpn_static_key }}"
      dest: /etc/openvpn/static.key
      mode: 0600
    when: openvpn_key.stat.exists != true and openvpn_static_key is defined
    tags:
      - configuration

  - name: copy openvpn static key variable
    command: cat /etc/openvpn/static.key
    tags:
      - configuration
    register: static_key

  - name: write openvpn static key to ansible tmp
    copy:
      content: "{{static_key.stdout}}"
      dest: ~/.ansible/tmp/static.key
    tags:
      - configuration 

  - name: copy openvpn client config
    template:
      src: openvpn-client.j2
      dest: /etc/openvpn/client.conf
      mode: 0600
    tags:
      - configuration

  - name: enable vpn client
    command: systemctl enable openvpn
    tags:
      - configuration

  - name: start vpn client
    command: systemctl start openvpn
    tags:
      - configuration
    when: start_vpn is defined
